// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkduDCjz7F-l3_yY4KUWV8Cd2G7cedwX8',
    appId: '1:771555012166:web:81494472a6ef622410e447',
    messagingSenderId: '771555012166',
    projectId: 'carcompany-848a1',
    authDomain: 'carcompany-848a1.firebaseapp.com',
    storageBucket: 'carcompany-848a1.firebasestorage.app',
    measurementId: 'G-5WL7YD4FR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaG7tS9Wpl7VC6OlY3YIJeRAPwLWXu4jg',
    appId: '1:771555012166:android:a948908543d20f9c10e447',
    messagingSenderId: '771555012166',
    projectId: 'carcompany-848a1',
    storageBucket: 'carcompany-848a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXU_PjHzGc1bOy6o9gkwFnvQGY4FA2PFc',
    appId: '1:771555012166:ios:69f393797199344a10e447',
    messagingSenderId: '771555012166',
    projectId: 'carcompany-848a1',
    storageBucket: 'carcompany-848a1.firebasestorage.app',
    iosBundleId: 'com.example.carcompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXU_PjHzGc1bOy6o9gkwFnvQGY4FA2PFc',
    appId: '1:771555012166:ios:69f393797199344a10e447',
    messagingSenderId: '771555012166',
    projectId: 'carcompany-848a1',
    storageBucket: 'carcompany-848a1.firebasestorage.app',
    iosBundleId: 'com.example.carcompany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkduDCjz7F-l3_yY4KUWV8Cd2G7cedwX8',
    appId: '1:771555012166:web:c679425c2af11d6510e447',
    messagingSenderId: '771555012166',
    projectId: 'carcompany-848a1',
    authDomain: 'carcompany-848a1.firebaseapp.com',
    storageBucket: 'carcompany-848a1.firebasestorage.app',
    measurementId: 'G-FVC5KDBZ2E',
  );
}
